sudo: required

language: ruby

services:
  - docker

script:
- make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t tweetatlas .;
    docker login -u "$HEROKU_USERNAME" -p "$HEROKU_PASSWORD" registry.heroku.com;
    docker tag tweetatlas registry.heroku.com/tweetatlas/web;
    docker push registry.heroku.com/tweetatlas/web;
    fi
